name: Linters
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - feature/workflows-and-linter
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - '**'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: app/