name: Linters
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - [main,feature/workflows-and-linter]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'logs/**'
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx