name: Tests

on:
  push:
    branches: [ feature/test-user-service-controller ]
  pull_request:
    branches: [ main ]

jobs:
  build:

  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
    uses: actions/checkout@v2
    with:
      fetch-depth: 2 

  - name: Set up Node.js 14.16
    uses: actions/setup-node@v1
    with:
        node-version: '14.16'

  - name: Install dependencies
    run: npm install

  - name: Run the tests
    run: npm test -- --coverage
