name: Tests

on:
  push:
    branches: [ feature/test-user-service-controller ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.16'
      - name: Install dependencies
        run: npm install
      - name: Install dependencies for codecov
      - name: Run the tests
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}